name: Frontend CI
permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Install Dependencies
      run: npm install

    # Optional: Add steps for linting JavaScript and CSS
    # - name: Lint JavaScript
    #   run: <your-js-linter-command>
    # - name: Lint CSS
    #   run: <your-css-linter-command>

    # Optional: Add steps for any tests you might have
    # - name: Run Tests
    #   run: <your-test-command>

    # Deployment step (example for GitHub Pages)
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./ # The folder the action should deploy.
